#API_KEY dari Twitter Developer

ACCESS_TOKEN = "ACCESS TOKEN KAMU"
ACCESS_TOKEN_SECRET = "ACCESS TOKEN SECRET KAMU"
CONSUMER_KEY = 'CONSUMER KEY KAMU'
CONSUMER_SECRET = 'CONSUMER SECRET KAMU'

BEARER_TOKEN = "BEARER TOKEN KAMU"
