#API_KEY dari Twitter Developer

ACCESS_TOKEN = "ACCESS TOKEN KAMU"
ACCESS_TOKEN_SECRET = "ACCESS TOKEN SECRET KAMU"
CONSUMER_KEY = 'CONSUMER KEY KAMU'
CONSUMER_SECRET = 'CONSUMER SECRET KAMU'
CALLBACK_URL = 'CALLBACK URL KAMU'
BEARER_TOKEN = "BEARER TOKEN KAMU"
CLIENT_ID = 'CLIENT ID KAMU'
